export const applogos = {
    logo: require('../../assets/logos/logoGreen.png'),
    AppLogo:require("../../assets/logos/AppLogo.png"),
    Googlelogo:require("../../assets/icons/google.png"),
    Facebooklogo:require("../../assets/icons/facebook.png")
};
export const appImages = {
    Discored: require('../../assets/images/Discord.png'),
    Email: require('../../assets/images/Email.png'),
    Facebook: require('../../assets/images/Facebook.png'),
    Github: require('../../assets/images/Github.png'),
    Instagram: require('../../assets/images/Instagram.png'),
    Linkedin: require('../../assets/images/Linkedin.png'),
    Map: require('../../assets/images/Map.png'),
    Nfc: require('../../assets/images/Nfc.png'),
    PhoneBook: require('../../assets/images/PhoneBook.png'),
    PhoneCall: require('../../assets/images/PhoneCall.png'),
    Pinterest: require('../../assets/images/Pinterest.png'),
    QrScan: require('../../assets/images/QrScan.png'),
    Reddit: require('../../assets/images/Reddit.png'),
    SnapChat: require('../../assets/images/SnapChat.png'),
    Spotify: require('../../assets/images/Spotify.png'),
    Text: require('../../assets/images/Text.png'),
    Tiktok: require('../../assets/images/Tiktok.png'),
    Twitter: require('../../assets/images/Twitter.png'),
    Url: require('../../assets/images/Url.png'),
    Youtube: require('../../assets/images/Youtube.png'),
    ButtonBackground: require('../../assets/images/ButtonBackground.png')
};

export const appIcons = {
    Read: require('../../assets/icons/Read.png'),
    Write: require('../../assets/icons/Write.png'),
    Locked: require('../../assets/icons/Locked.png'),
    QrClick: require('../../assets/icons/QrClick.png'),
    Flash: require('../../assets/icons/Flash.png'),
    SelectImage: require('../../assets/icons/SelectImage.png'),
    Setting: require('../../assets/icons/Setting.png'),
    SocialLinks: require('../../assets/icons/SocialLinks.png'),
    Next: require('../../assets/icons/Next.png'),
    Eye: require('../../assets/icons/Eye.png'),
    Back: require('../../assets/icons/Back.png'),
    About: require('../../assets/icons/About.png'),
    Edit: require('../../assets/icons/Edit.png'),
    Delete: require('../../assets/icons/Delete.png'),
    Rate: require('../../assets/icons/Rate.png'),
    ContactUs: require('../../assets/icons/ContactUs.png'),
    PrivacyPolicy: require('../../assets/icons/PrivacyPolicy.png'),
    Share: require('../../assets/icons/Share.png'),
    Support: require('../../assets/icons/Support.png'),
    Search: require('../../assets/icons/Search.png'),
    DeleteAccount: require('../../assets/icons/DeleteAccount.png'),
    Logout: require('../../assets/icons/Logout.png'),
    Down: require('../../assets/icons/Down.png'),
    Up: require('../../assets/icons/Up.png'),
    Information: require('../../assets/icons/Information.png'),
    Chatbot: require('../../assets/icons/Chatbot.png'),
    Tips: require('../../assets/icons/Tips.png'),
    Bug: require('../../assets/icons/Bug.png'),
    Protect: require('../../assets/icons/Bug.png'),
    Lock: require('../../assets/icons/Protect.png'),
    Fire: require('../../assets/icons/Fire.png'),
    PrivacyPolicyIcon: require('../../assets/icons/PrivacyPolicyIcon.png'),
    AboutBlue: require('../../assets/icons/AboutBlue.png'),
    Dot: require('../../assets/icons/Dot.png'),
    EyeOff: require('../../assets/icons/Eye-Off.png')
}

